### PR TITLE
fix: exit app after qs tile recording launch

### LINKED ISSUE #186: App shouldn't launch when recording with Quick Settings
### Steps to reproduce

1. Click Record option from Quick Settings.
2. The app is launched

### Expected behavior

The app shouldn't launch and only the corresponding recording should start.

### Actual behavior

The app opens.

### Record You version

All released versions

### Android version

Probably all

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ghost**
Currently only works for screen recording
Hence #207 still exist for audio

Don't know how to get activity for media projection manager without launching it😅

closes #186

### CODE REVIEW

File: app/src/main/java/com/bnyro/recorder/ui/MainActivity.kt [hunk 1]
```diff
@@ -16,12 +16,13 @@ import com.bnyro.recorder.ui.models.ThemeModel
 import com.bnyro.recorder.ui.theme.RecordYouTheme
 
 class MainActivity : ComponentActivity() {
+    private var initialRecorder = RecorderType.NONE
+    private var exit = false
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/recorder/ui/MainActivity.kt:20]:
```suggestion
    private var exitAfterRecordingStart = false
```
sounds more self-explaining

File: app/src/main/java/com/bnyro/recorder/ui/MainActivity.kt [hunk 2]
```diff
@@ -16,12 +16,13 @@ import com.bnyro.recorder.ui.models.ThemeModel
...
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
-
         val themeModel: ThemeModel by viewModels()
 
-        val initialRecorder = when (intent?.getStringExtra("action")) {
+        initialRecorder = when (intent?.getStringExtra("action")) {
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/recorder/ui/MainActivity.kt:25]: Please move "action" to a constant and re-use it everywhere else where we use "action".

**Comment by Bnyro** [comment]
Sorry for the delay btw, I've addressed the review myself.
